services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      ADDRESS: ":8080"
    #! CREATE 'king.db' BEFORE CREATING CONTAINER
    volumes:
      - "./king.db:/opt/king/king.db"
