name: Notify on push

on:
  push:
  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: Formula-SAE/notify-push@v1.2
        with:
          event: ${{ toJson(github.event) }}
          apiToken: ${{ secrets.API_TOKEN }}
          apiUrl: ${{ secrets.API_URL }}
          providers: ${{ secrets.PROVIDERS }}
